---
application:
  name: "resto-beep"
  project: "resto-beep"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 8080
routers:
- name: "main-resto-beep"
  routes:
  - application_name: "resto-beep"
    paths:
    - "/*"
